base_url = "https://harshul-s.github.io/"
generate_feed = true
build_search_index = true
title = "portfolio"
compile_sass = true
description = "A clean resume theme"

[markdown]
highlight_code = true
highlight_theme = "OneHalfLight"

[[taxonomies]]
name = "tags"
feed = true

[extra]
show_blog = true
show_skills = true
show_education = true
show_opensource = false
show_publications = false
show_about = true
show_experience = false
phone = " "
katex = false
favicon = "/media/h.png"
last_name = "Singh"
address = "Seattle"
avatar = "/media/avatar.png"
first_name = "Harshul"
show_projects = true
email = "hsingh0916@gmail.com"